### ISSUE TITLE
Multiple line

### ISSUE THREAD

**Issue by cadelisme** [ilhamsuaib/Android-Print-Bluetooth#3]
Bisakan dibuat multipleline? seperti adanya header dan footer.
seperti struk belanja. terimakasih banyak.

**Comment by ilhamsuaib** [comment]
bisa... untuk new line & text alignment bisa menggunakan printer commands
https://github.com/ilhamsuaib/Android-Print-Bluetooth/blob/master/app/src/main/java/id/ilhamsuaib/androidprintbluetooth/PrinterCommands.java

**Comment by cadelisme** [comment]
public static byte[] FEED_LINE = {10}; ini untuk new linenya ya? 
berarti klo multilinenya itu seperti ini ya: 

            mService.write(PrinterCommands.ESC_ALIGN_CENTER);
            mService.sendMessage(etText.getText().toString(), "");
            mService.write(PrinterCommands.FEED_LINE);
            mService.sendMessage("STRING LAGI");

            mService.write(PrinterCommands.FEED_LINE);
            mService.sendMessage("STRING LAGI");

            mService.write(PrinterCommands.FEED_LINE);
            mService.sendMessage("STRING LAGI");
            mService.write(PrinterCommands.ESC_ENTER);


makasih banyak mas.

**Comment by ilhamsuaib** [comment]
Iya... Sama2
