### ISSUE TITLE
Aplikasi Error

### ISSUE THREAD

**Issue by tri82wiyono** [ilhamsuaib/Android-Print-Bluetooth#4]
gan aplikasi setelah saya build langsung ke tutup aplikasnya dan saya cek logcat muncul pesan 
     Caused by: java.lang.IllegalStateException: Required view 'et_text' with ID 2131230818 for field 'etText' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
 tapi udah saya sesuaikan masih nggak mau juga

**Comment by tri82wiyono** [comment]
sudah solve, cuma kenapa ya misalnya sudah bisa print sekali jika aplikasi androd saya tututp tidak bisa print, ketika saya klik tombol print disuruh pilih printernya lagi, tapi gagal tidak dapat terhubung ke perangkat.

**Comment by cadelisme** [comment]
mas @tri82wiyono boleh saya tau mas bikin aplikasi sejenis apa? saya ada tugas kuliah untuk bikin mesin kasir mini yg bisa outputnya itu keluar print struk seperrti di minimarket dll. apakah mas membeuat hal sama? terimaksih.

**Comment by tri82wiyono** [comment]
saya buat aplikasi slip penarikan dan setoran online, biasanya kalau kita ke bank mau tarik tunai harus isi slip di kertas form yang da bank sediakan. jadi itu mau di hilangkan digantikan oleh system dengan android pakai tablet gitu mas. nah nanti outputnya ada nomor tiket kemudian di cetak

**Comment by cadelisme** [comment]
Mas untuk hasil print supaya bisa multiline gimna ya? saya punya data berupa int, saya ingin multine sebanyak data yg saya punya, sedangkan dalam Class PrintCommend harus berupa byte[ ]. terimaksih banyak.

**Comment by ilhamsuaib** [comment]
Thanks @tri82wiyono
