### ISSUE TITLE
How To Make Left and Right Text Align In One Row ?

### ISSUE THREAD

**Issue by Mfdsix** [ilhamsuaib/Android-Print-Bluetooth#7]
i wanna make invoice template with this example, but i got stuck in make inline left and right text alignment.

for example i have this format

Description         Nominal
Payment A          $ 5.0
Payment A          $ 5.0
Payment A          $ 5.0
Total                    $ 15.0

**Comment by romichoirudin33** [comment]
you can try it with string format. cause printer just print a one row.

`String text = String.format("%10s %5s", "Payment A", "$ 5.0");`
`String text = String.format("%10s %5s", "Total", "$ 15.0");`
